#!/bin/bash -x
# Redis local

REPO_ROOT="$HOME/Documents/Dev/repos"
REDIS_SERVER="$REPO_ROOT/community/redis/src/redis-server"
REDIS_CONFIG="$REPO_ROOT/iotbzh/rp-service-hiredis/scripts/redis.conf"

WD="$REPO_ROOT/iotbzh/rp-service-hiredis/build"

$REDIS_SERVER $REDIS_CONFIG &

afb-binder --name redis --port=1236 --workdir=$WD \
--binding=package/lib/redis-binding.so \
--roothttp=package/htdocs --tracereq=common -vvv \
--monitor \
--ws-server=unix:/tmp/redis
