#!/bin/bash -x
# Redis cloud

if [[ "$1" == "debug" ]]; then
    GDB="gdb --args"
    #export AFB_DEBUG_BREAK=main-entry
fi

BASE="/root"

$BASE/redis-server $BASE/redis-cloud-container.conf &

export CONTROL_CONFIG_PATH=/root
$GDB afb-binder --name redis-cloud --port=1235 --workdir=$BASE \
--binding=$BASE/redis-binding.so \
--roothttp=$BASE/htdocs --tracereq=common -vvv \
--monitor \
--ws-server=tcp:localhost:1212/redis
