#!/bin/bash -x
# Redis cloud

if [[ "$1" == "debug" ]]; then
    GDB="gdb --args"
    #export AFB_DEBUG_BREAK=main-entry
fi

REPO_ROOT="$HOME/Documents/Dev/repos"
REDIS_SERVER="$REPO_ROOT/community/redis/src/redis-server"
REDIS_CONFIG="$REPO_ROOT/iotbzh/rp-service-hiredis/scripts/redis-cloud.conf"

WD="$REPO_ROOT/iotbzh/rp-service-hiredis/build"

$REDIS_SERVER $REDIS_CONFIG &

# Note that --name and prefix in binding itself must align to compose config
# filename, here redis-binding-cloud for --name=redis-cloud and
# prefix=redis-binding
$GDB afb-daemon --name redis-cloud --port=1235 --workdir=$WD \
--ldpath=/dev/null --binding=package/lib/redis-binding.so \
--roothttp=package/htdocs --token= --tracereq=common -vvv \
--monitor \
--ws-server=tcp:localhost:1212/redis
